import type { Metadata } from "next";
import "./globals.css";
import { rubik } from '@/app/ui/fonts'

export const metadata: Metadata = {
  title: "Little Scout",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
